# DESCRIPTION: GitLab CI/CD for libRetro (NOT FOR GitLab-proper)

##############################################################################
################################# BOILERPLATE ################################
##############################################################################

# Core definitions
.core-defs:
  variables:
    MAKEFILE_PATH: tools/package/libretro
    CORENAME: virtualxt

# Inclusion templates, required for the build to work
include:
  ################################## DESKTOPS ################################
  # Windows 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-x64-mingw.yml'
    
  # Windows 32-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-i686-mingw.yml'

  # Linux 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-x64.yml'

  # Linux 32-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-i686.yml'

  # MacOS 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/osx-x64.yml'

  # MacOS ARM 64-bit
  - project: 'libretro-infrastructure/ci-templates'
    file: '/osx-arm64.yml'

  ################################## CELLULAR ################################
  # Android
  - project: 'libretro-infrastructure/ci-templates'
    file: '/android-make.yml'

  # iOS
  - project: 'libretro-infrastructure/ci-templates'
    file: '/ios-arm64.yml'

  # iOS (armv7)
  - project: 'libretro-infrastructure/ci-templates'
    file: '/ios9.yml'

  # tvOS
  - project: 'libretro-infrastructure/ci-templates'
    file: '/tvos-arm64.yml'

  #################################### MISC ##################################
  # Emscripten
  - project: 'libretro-infrastructure/ci-templates'
    file: '/emscripten-static.yml'

# Stages for building
stages:
  - build-prepare
  - build-shared
  - build-static

##############################################################################
#################################### STAGES ##################################
##############################################################################
#
################################### DESKTOPS #################################
# Windows 64-bit
libretro-build-windows-x64:
  only:
    - edge
    - release
  extends:
    - .libretro-windows-x64-mingw-make-default
    - .core-defs
    
# Windows 32-bit
libretro-build-windows-i686:
  only:
    - edge
    - release
  extends:
    - .libretro-windows-i686-mingw-make-default
    - .core-defs

# Linux 64-bit
libretro-build-linux-x64:
  only:
    - develop
    - edge
    - release
  extends:
    - .libretro-linux-x64-make-default
    - .core-defs

# Linux 32-bit
libretro-build-linux-i686:
  only:
    - edge
    - release
  extends:
    - .libretro-linux-i686-make-default
    - .core-defs

# MacOS 64-bit
libretro-build-osx-x64:
  only:
    - edge
    - release
  extends:
    - .libretro-osx-x64-make-default
    - .core-defs

# MacOS ARM 64-bit
libretro-build-osx-arm64:
  only:
    - edge
    - release
  extends:
    - .libretro-osx-arm64-make-default
    - .core-defs

################################### CELLULAR #################################
# Android ARMv7a
android-armeabi-v7a:
  only:
    - edge
    - release
  extends:
    - .libretro-android-make-armeabi-v7a
    - .core-defs

# Android ARMv8a
android-arm64-v8a:
  only:
    - edge
    - release
  extends:
    - .libretro-android-make-arm64-v8a
    - .core-defs

# Android 64-bit x86
android-x86_64:
  only:
    - edge
    - release
  extends:
    - .libretro-android-make-x86_64
    - .core-defs
    
# Android 32-bit x86
android-x86:
  only:
    - edge
    - release
  extends:
    - .libretro-android-make-x86
    - .core-defs

# iOS
libretro-build-ios-arm64:
  only:
    - edge
    - release
  extends:
    - .libretro-ios-arm64-make-default
    - .core-defs

# iOS (armv7) [iOS 9 and up]
libretro-build-ios9:
  only:
    - edge
    - release
  extends:
    - .libretro-ios9-make-default
    - .core-defs

# tvOS
libretro-build-tvos-arm64:
  only:
    - edge
    - release
  extends:
    - .libretro-tvos-arm64-make-default
    - .core-defs

#################################### MISC ##################################
# Emscripten
libretro-build-emscripten:
  only:
    - edge
    - release
  extends:
    - .libretro-emscripten-static-retroarch-master
    - .core-defs
